-- PrimeQA Migration 030: run tags + AI failure summary.
--
-- Two small additions to pipeline_runs that unlock three high-pain
-- run-experience features:
--
--   1. `label` VARCHAR(100) \u2014 free-form tag for filtering run history
--      ("release SQ-211 smoke", "nightly regression", "pre-merge").
--      Partial index for fast filtering excludes the common NULL case.
--
--   2. `failure_summary_ai` TEXT \u2014 on-demand AI rollup of why tests
--      failed, generated by clicking "Summarise failures" on run detail.
--      Cached here so repeated page loads don't re-prompt the LLM. A
--      separate `failure_summary_at` captures when the summary was
--      computed so the UI can offer "Regenerate" if new steps finished
--      after the last summary.
--
-- The "Run verbatim" feature doesn't need a new column \u2014 it just
-- stores test_case_version_ids inside the existing source_refs JSONB
-- when queuing a rerun, and resolves by (test_case_id, version_id)
-- instead of (test_case_id + current_version) at execution time.
--
-- Idempotent.

BEGIN;

ALTER TABLE pipeline_runs
    ADD COLUMN IF NOT EXISTS label VARCHAR(100),
    ADD COLUMN IF NOT EXISTS failure_summary_ai TEXT,
    ADD COLUMN IF NOT EXISTS failure_summary_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS failure_summary_model VARCHAR(100);

-- Fast filter: "show me all runs tagged release-smoke in this tenant"
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_label
    ON pipeline_runs (tenant_id, label)
    WHERE label IS NOT NULL;

COMMIT;
