-- 063: S5 rule-catalogue SEED — axe-core 4.13.0 -> WCAG 2.2 (LLD 3A-1 §3).
-- GENERATED by scripts/gen_s5_seed.py from migrations/seeds/s5_rule_seed_axe4130_wcag22.json — edit the
-- generator/fixture, never this file by hand. Idempotent (ON CONFLICT
-- DO NOTHING); re-run is a no-op. Seeded rows are the DECLARED bootstrap
-- exception: v1 direct-to-ACTIVE with seed_provenance.bootstrap=true;
-- the service layer refuses that state for any non-bootstrap row.
BEGIN;
INSERT INTO s5_artifacts (kind, name, version, sha256, repo_path, source_url, byte_size)
VALUES ('engine', 'axe-core', '4.13.0', 'c24f097bd2f451d4f933e8bc7d8d539f8672a2ebcb5cc9f9f3eec8ca9470a0c1', 'primeqa/browser_worker/vendor/axe.min.js',
        'https://registry.npmjs.org/axe-core/-/axe-core-4.13.0.tgz', 580491)
ON CONFLICT (kind, name, version) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-001', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-001', 1, 'Active <area> elements must have alternative text', 'Ensure <area> elements of image maps have alternative text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "area-alt", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-001', 1, 'axe-core', '4.13.0', 'area-alt')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-001', 1, 'WCAG22', '2.4.4', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-001', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-002', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-002', 1, 'Elements must only use supported ARIA attributes', 'Ensure an element''s role supports its ARIA attributes', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-allowed-attr", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-002', 1, 'axe-core', '4.13.0', 'aria-allowed-attr')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-002', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-003', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-003', 1, 'aria-braille attributes must have a non-braille equivalent', 'Ensure aria-braillelabel and aria-brailleroledescription have a non-braille equivalent', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-braille-equivalent", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-003', 1, 'axe-core', '4.13.0', 'aria-braille-equivalent')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-003', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-004', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-004', 1, 'ARIA commands must have an accessible name', 'Ensure every ARIA button, link and menuitem has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-command-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-004', 1, 'axe-core', '4.13.0', 'aria-command-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-004', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-005', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-005', 1, 'ARIA attributes must be used as specified for the element''s role', 'Ensure ARIA attributes are used as described in the specification of the element''s role', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-conditional-attr", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-005', 1, 'axe-core', '4.13.0', 'aria-conditional-attr')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-005', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-006', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-006', 1, 'Deprecated ARIA roles must not be used', 'Ensure elements do not use deprecated roles', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-deprecated-role", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-006', 1, 'axe-core', '4.13.0', 'aria-deprecated-role')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-006', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-007', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-007', 1, 'aria-hidden="true" must not be present on the document body', 'Ensure aria-hidden="true" is not present on the document body.', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-hidden-body", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-007', 1, 'axe-core', '4.13.0', 'aria-hidden-body')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-007', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-007', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-008', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-008', 1, 'ARIA hidden element must not be focusable or contain focusable elements', 'Ensure aria-hidden elements are not focusable nor contain focusable elements', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-hidden-focus", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-008', 1, 'axe-core', '4.13.0', 'aria-hidden-focus')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-008', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-009', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-009', 1, 'ARIA input fields must have an accessible name', 'Ensure every ARIA input field has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-input-field-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-009', 1, 'axe-core', '4.13.0', 'aria-input-field-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-009', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-010', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-010', 1, 'ARIA meter nodes must have an accessible name', 'Ensure every ARIA meter node has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-meter-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-010', 1, 'axe-core', '4.13.0', 'aria-meter-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-010', 1, 'WCAG22', '1.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-011', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-011', 1, 'ARIA progressbar nodes must have an accessible name', 'Ensure every ARIA progressbar node has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-progressbar-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-011', 1, 'axe-core', '4.13.0', 'aria-progressbar-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-011', 1, 'WCAG22', '1.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-012', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-012', 1, 'Elements must only use permitted ARIA attributes', 'Ensure ARIA attributes are not prohibited for an element''s role', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-prohibited-attr", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-012', 1, 'axe-core', '4.13.0', 'aria-prohibited-attr')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-012', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-013', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-013', 1, 'Required ARIA attributes must be provided', 'Ensure elements with ARIA roles have all required ARIA attributes', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-required-attr", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-013', 1, 'axe-core', '4.13.0', 'aria-required-attr')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-013', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-014', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-014', 1, 'Certain ARIA roles must contain particular children', 'Ensure elements with an ARIA role that require child roles contain them', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-required-children", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-014', 1, 'axe-core', '4.13.0', 'aria-required-children')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-014', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-015', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-015', 1, 'Certain ARIA roles must be contained by particular parents', 'Ensure elements with an ARIA role that require parent roles are contained by them', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-required-parent", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-015', 1, 'axe-core', '4.13.0', 'aria-required-parent')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-015', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-016', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-016', 1, 'aria-roledescription must be on elements with a semantic role', 'Ensure aria-roledescription is only used on elements with an implicit or explicit role', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-roledescription", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-016', 1, 'axe-core', '4.13.0', 'aria-roledescription')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-016', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-017', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-017', 1, 'ARIA roles used must conform to valid values', 'Ensure all elements with a role attribute use a valid value', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-roles", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-017', 1, 'axe-core', '4.13.0', 'aria-roles')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-017', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-018', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-018', 1, 'ARIA tab nodes must have an accessible name', 'Ensure every ARIA tab node has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-tab-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-018', 1, 'axe-core', '4.13.0', 'aria-tab-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-018', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-019', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-019', 1, 'ARIA toggle fields must have an accessible name', 'Ensure every ARIA toggle field has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-toggle-field-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-019', 1, 'axe-core', '4.13.0', 'aria-toggle-field-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-019', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-020', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-020', 1, 'ARIA tooltip nodes must have an accessible name', 'Ensure every ARIA tooltip node has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-tooltip-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-020', 1, 'axe-core', '4.13.0', 'aria-tooltip-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-020', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-021', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-021', 1, 'ARIA attributes must conform to valid names', 'Ensure attributes that begin with aria- are valid ARIA attributes', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-valid-attr", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-021', 1, 'axe-core', '4.13.0', 'aria-valid-attr')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-021', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-022', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-022', 1, 'ARIA attributes must conform to valid values', 'Ensure all ARIA attributes have valid values', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "aria-valid-attr-value", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-022', 1, 'axe-core', '4.13.0', 'aria-valid-attr-value')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-022', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-023', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-023', 1, '<audio> elements must have a captions track', 'Ensure <audio> elements have captions', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "audio-caption", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-023', 1, 'axe-core', '4.13.0', 'audio-caption')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-023', 1, 'WCAG22', '1.2.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-024', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-024', 1, 'autocomplete attribute must be used correctly', 'Ensure the autocomplete attribute is correct and suitable for the form field', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "autocomplete-valid", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-024', 1, 'axe-core', '4.13.0', 'autocomplete-valid')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-024', 1, 'WCAG22', '1.3.5', 'AA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-025', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-025', 1, 'Inline text spacing must be adjustable with custom stylesheets', 'Ensure that text spacing set through style attributes can be adjusted with custom stylesheets', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "avoid-inline-spacing", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-025', 1, 'axe-core', '4.13.0', 'avoid-inline-spacing')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-025', 1, 'WCAG22', '1.4.12', 'AA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-026', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-026', 1, '<blink> elements are deprecated and must not be used', 'Ensure <blink> elements are not used', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "blink", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-026', 1, 'axe-core', '4.13.0', 'blink')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-026', 1, 'WCAG22', '2.2.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-027', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-027', 1, 'Buttons must have discernible text', 'Ensure buttons have discernible text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "button-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-027', 1, 'axe-core', '4.13.0', 'button-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-027', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-028', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-028', 1, 'Page must have means to bypass repeated blocks', 'Ensure each page has at least one mechanism for a user to bypass navigation and jump straight to the content', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "bypass", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-028', 1, 'axe-core', '4.13.0', 'bypass')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-028', 1, 'WCAG22', '2.4.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-029', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-029', 1, 'Elements must meet minimum color contrast ratio thresholds', 'Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "color-contrast", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-029', 1, 'axe-core', '4.13.0', 'color-contrast')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-029', 1, 'WCAG22', '1.4.3', 'AA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-030', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-030', 1, 'Elements must meet enhanced color contrast ratio thresholds', 'Ensure the contrast between foreground and background colors meets WCAG 2 AAA enhanced contrast ratio thresholds', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "color-contrast-enhanced", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-030', 1, 'axe-core', '4.13.0', 'color-contrast-enhanced')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-030', 1, 'WCAG22', '1.4.6', 'AAA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-031', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-031', 1, '<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements', 'Ensure <dl> elements are structured correctly', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "definition-list", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-031', 1, 'axe-core', '4.13.0', 'definition-list')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-031', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-032', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-032', 1, '<dt> and <dd> elements must be contained by a <dl>', 'Ensure <dt> and <dd> elements are contained by a <dl>', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "dlitem", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-032', 1, 'axe-core', '4.13.0', 'dlitem')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-032', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-033', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-033', 1, 'Documents must have <title> element to aid in navigation', 'Ensure each HTML document contains a non-empty <title> element', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "document-title", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-033', 1, 'axe-core', '4.13.0', 'document-title')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-033', 1, 'WCAG22', '2.4.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-034', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-034', 1, 'IDs used in ARIA and labels must be unique', 'Ensure every id attribute value used in ARIA and in labels is unique', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "duplicate-id-aria", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-034', 1, 'axe-core', '4.13.0', 'duplicate-id-aria')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-034', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-035', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-035', 1, 'Form field must not have multiple label elements', 'Ensure form field does not have multiple label elements', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "form-field-multiple-labels", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-035', 1, 'axe-core', '4.13.0', 'form-field-multiple-labels')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-035', 1, 'WCAG22', '3.3.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-036', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-036', 1, 'Frames with focusable content must not have tabindex=-1', 'Ensure <frame> and <iframe> elements with focusable content do not have tabindex=-1', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "frame-focusable-content", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-036', 1, 'axe-core', '4.13.0', 'frame-focusable-content')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-036', 1, 'WCAG22', '2.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-037', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-037', 1, 'Frames must have an accessible name', 'Ensure <iframe> and <frame> elements have an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "frame-title", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-037', 1, 'axe-core', '4.13.0', 'frame-title')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-037', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-038', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-038', 1, 'Frames must have a unique title attribute', 'Ensure <iframe> and <frame> elements contain a unique title attribute', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "frame-title-unique", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-038', 1, 'axe-core', '4.13.0', 'frame-title-unique')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-038', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-039', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-039', 1, '<html> element must have a lang attribute', 'Ensure every HTML document has a lang attribute', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "html-has-lang", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-039', 1, 'axe-core', '4.13.0', 'html-has-lang')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-039', 1, 'WCAG22', '3.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-040', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-040', 1, '<html> element must have a valid value for the lang attribute', 'Ensure the lang attribute of the <html> element has a valid value', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "html-lang-valid", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-040', 1, 'axe-core', '4.13.0', 'html-lang-valid')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-040', 1, 'WCAG22', '3.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-041', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-041', 1, 'HTML elements with lang and xml:lang must have the same base language', 'Ensure that HTML elements with both valid lang and xml:lang attributes agree on the base language of the page', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "html-xml-lang-mismatch", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-041', 1, 'axe-core', '4.13.0', 'html-xml-lang-mismatch')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-041', 1, 'WCAG22', '3.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-042', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-042', 1, 'Links with the same name must have a similar purpose', 'Ensure that links with the same accessible name serve a similar purpose', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "identical-links-same-purpose", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-042', 1, 'axe-core', '4.13.0', 'identical-links-same-purpose')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-042', 1, 'WCAG22', '2.4.9', 'AAA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-043', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-043', 1, 'Images must have alternative text', 'Ensure <img> elements have alternative text or a role of none or presentation', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "image-alt", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-043', 1, 'axe-core', '4.13.0', 'image-alt')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-043', 1, 'WCAG22', '1.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-044', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-044', 1, 'Input buttons must have discernible text', 'Ensure input buttons have discernible text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "input-button-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-044', 1, 'axe-core', '4.13.0', 'input-button-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-044', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-045', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-045', 1, 'Image buttons must have alternative text', 'Ensure <input type="image"> elements have alternative text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "input-image-alt", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-045', 1, 'axe-core', '4.13.0', 'input-image-alt')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-045', 1, 'WCAG22', '1.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-045', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-046', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-046', 1, 'Form elements must have labels', 'Ensure every form element has a label', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "label", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-046', 1, 'axe-core', '4.13.0', 'label')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-046', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-047', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-047', 1, 'Links must be distinguishable without relying on color', 'Ensure links are distinguished from surrounding text in a way that does not rely on color', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "link-in-text-block", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-047', 1, 'axe-core', '4.13.0', 'link-in-text-block')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-047', 1, 'WCAG22', '1.4.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-048', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-048', 1, 'Links must have discernible text', 'Ensure links have discernible text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "link-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-048', 1, 'axe-core', '4.13.0', 'link-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-048', 1, 'WCAG22', '2.4.4', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-048', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-049', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-049', 1, '<ul> and <ol> must only directly contain <li>, <script> or <template> elements', 'Ensure that lists are structured correctly', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "list", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-049', 1, 'axe-core', '4.13.0', 'list')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-049', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-050', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-050', 1, '<li> elements must be contained in a <ul> or <ol>', 'Ensure <li> elements are used semantically', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "listitem", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-050', 1, 'axe-core', '4.13.0', 'listitem')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-050', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-051', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-051', 1, '<marquee> elements are deprecated and must not be used', 'Ensure <marquee> elements are not used', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "marquee", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-051', 1, 'axe-core', '4.13.0', 'marquee')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-051', 1, 'WCAG22', '2.2.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-052', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-052', 1, 'Delayed refresh under 20 hours must not be used', 'Ensure <meta http-equiv="refresh"> is not used for delayed refresh', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "meta-refresh", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-052', 1, 'axe-core', '4.13.0', 'meta-refresh')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-052', 1, 'WCAG22', '2.2.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-053', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-053', 1, 'Delayed refresh must not be used', 'Ensure <meta http-equiv="refresh"> is not used for delayed refresh', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "meta-refresh-no-exceptions", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-053', 1, 'axe-core', '4.13.0', 'meta-refresh-no-exceptions')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-053', 1, 'WCAG22', '2.2.4', 'AAA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-053', 1, 'WCAG22', '3.2.5', 'AAA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-054', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-054', 1, 'Zooming and scaling must not be disabled', 'Ensure <meta name="viewport"> does not disable text scaling and zooming', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "meta-viewport", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-054', 1, 'axe-core', '4.13.0', 'meta-viewport')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-054', 1, 'WCAG22', '1.4.4', 'AA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-055', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-055', 1, 'Interactive controls must not be nested', 'Ensure interactive controls are not nested as they are not always announced by screen readers or can cause focus problems for assistive technologies', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "nested-interactive", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-055', 1, 'axe-core', '4.13.0', 'nested-interactive')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-055', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-056', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-056', 1, '<video> or <audio> elements must not play automatically', 'Ensure <video> or <audio> elements do not autoplay audio for more than 3 seconds without a control mechanism to stop or mute the audio', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "no-autoplay-audio", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-056', 1, 'axe-core', '4.13.0', 'no-autoplay-audio')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-056', 1, 'WCAG22', '1.4.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-057', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-057', 1, '<object> elements must have alternative text', 'Ensure <object> elements have alternative text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "object-alt", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-057', 1, 'axe-core', '4.13.0', 'object-alt')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-057', 1, 'WCAG22', '1.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-058', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-058', 1, '[role="img"] and [role="image"] elements must have alternative text', 'Ensure [role="img"] and [role="image"] elements have alternative text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "role-img-alt", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-058', 1, 'axe-core', '4.13.0', 'role-img-alt')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-058', 1, 'WCAG22', '1.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-059', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-059', 1, 'Scrollable region must have keyboard access', 'Ensure elements that have scrollable content are accessible by keyboard in Safari', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "scrollable-region-focusable", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-059', 1, 'axe-core', '4.13.0', 'scrollable-region-focusable')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-059', 1, 'WCAG22', '2.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-059', 1, 'WCAG22', '2.1.3', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-060', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-060', 1, 'Select element must have an accessible name', 'Ensure select element has an accessible name', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "select-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-060', 1, 'axe-core', '4.13.0', 'select-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-060', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-061', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-061', 1, 'Server-side image maps must not be used', 'Ensure that server-side image maps are not used', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "server-side-image-map", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-061', 1, 'axe-core', '4.13.0', 'server-side-image-map')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-061', 1, 'WCAG22', '2.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-062', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-062', 1, 'Summary elements must have discernible text', 'Ensure summary elements have discernible text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "summary-name", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-062', 1, 'axe-core', '4.13.0', 'summary-name')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-062', 1, 'WCAG22', '4.1.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-063', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-063', 1, '<svg> elements with an img or image role must have alternative text', 'Ensure <svg> elements with an img, image, graphics-document or graphics-symbol role have accessible text', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "svg-img-alt", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-063', 1, 'axe-core', '4.13.0', 'svg-img-alt')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-063', 1, 'WCAG22', '1.1.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-064', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-064', 1, 'All touch targets must be 24px large, or leave sufficient space', 'Ensure touch targets have sufficient size and space', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "target-size", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-064', 1, 'axe-core', '4.13.0', 'target-size')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-064', 1, 'WCAG22', '2.5.8', 'AA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-065', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-065', 1, 'Table cell headers attributes must refer to other <th> elements in the same table', 'Ensure that each cell in a table that uses the headers attribute refers only to other <th> elements in that table', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "td-headers-attr", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-065', 1, 'axe-core', '4.13.0', 'td-headers-attr')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-065', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-066', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-066', 1, 'Table headers in a data table must refer to data cells', 'Ensure that <th> elements and elements with role=columnheader/rowheader have data cells they describe', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "th-has-data-cells", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-066', 1, 'axe-core', '4.13.0', 'th-has-data-cells')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-066', 1, 'WCAG22', '1.3.1', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-067', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-067', 1, 'lang attribute must have a valid value', 'Ensure lang attributes have valid values', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "valid-lang", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-067', 1, 'axe-core', '4.13.0', 'valid-lang')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-067', 1, 'WCAG22', '3.1.2', 'AA')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
INSERT INTO s5_rules (rule_id, owner) VALUES ('PLM-A11Y-068', 'plimsol') ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO s5_rule_versions (rule_id, version, name, description, automation_capability, human_review_required, state, seed_provenance)
VALUES ('PLM-A11Y-068', 1, '<video> elements must have captions', 'Ensure <video> elements have captions', 'AUTO', FALSE, 'ACTIVE', '{"bootstrap": true, "engine_rule_id": "video-caption", "derived_from": "axe-core 4.13.0"}'::jsonb)
ON CONFLICT (rule_id, version) DO NOTHING;
INSERT INTO s5_engine_bindings (rule_id, rule_version, engine, engine_version, engine_rule_id)
VALUES ('PLM-A11Y-068', 1, 'axe-core', '4.13.0', 'video-caption')
ON CONFLICT (rule_id, rule_version, engine, engine_version, engine_rule_id) DO NOTHING;
INSERT INTO s5_standard_maps (rule_id, rule_version, standard, criterion, level)
VALUES ('PLM-A11Y-068', 1, 'WCAG22', '1.2.2', 'A')
ON CONFLICT (rule_id, rule_version, standard, criterion) DO NOTHING;
-- catalogue release 1: the D-461 pin target; membership RECORDED (D-281 law)
INSERT INTO s5_catalogue_releases (id, notes, content_hash)
VALUES (1, 'R1 seed release: axe-core 4.13.0 -> WCAG 2.2, 68 rules', '9c80abdccb3fc23bc130673743319d0892adec837afd363a0ba4bc894bcf0812')
ON CONFLICT (id) DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-001', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-002', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-003', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-004', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-005', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-006', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-007', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-008', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-009', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-010', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-011', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-012', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-013', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-014', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-015', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-016', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-017', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-018', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-019', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-020', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-021', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-022', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-023', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-024', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-025', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-026', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-027', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-028', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-029', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-030', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-031', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-032', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-033', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-034', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-035', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-036', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-037', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-038', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-039', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-040', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-041', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-042', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-043', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-044', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-045', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-046', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-047', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-048', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-049', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-050', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-051', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-052', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-053', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-054', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-055', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-056', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-057', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-058', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-059', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-060', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-061', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-062', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-063', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-064', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-065', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-066', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-067', 1) ON CONFLICT DO NOTHING;
INSERT INTO s5_catalogue_release_members (release_id, rule_id, rule_version) VALUES (1, 'PLM-A11Y-068', 1) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('s5_catalogue_releases','id'), GREATEST((SELECT MAX(id) FROM s5_catalogue_releases), 1));
COMMIT;
