#!/usr/bin/env python3
"""Authorization inventory — the LIVE oracle (authz-role-ladder, D-245; rebuilt
in round 3 for AUD-001).

The first oracle read decorator NAMES out of the AST, so a gate imported
under an alias (``from primeqa.core.auth import require_auth as
_require_auth_api``) was invisible: three authenticated routes were reported
as "(none — auth/login only or open)" while they carried the gate. An oracle
that can be green while a route is open, or red while it is gated, is a
self-reporting control.

This one derives every gate from the RUNNING app: it imports the Flask app,
walks each endpoint's view function through ``__wrapped__`` AND every function
held in a closure cell (a decorator's inner function lives in a cell, not on
the ``__wrapped__`` chain), and recognises a gate by the CODE OBJECT of the
wrapper it produces — never by a name, which ``functools.wraps`` copies and an
alias hides. The Tier a ladder gate enforces is read from the closure cell that
holds it. ``role_required`` / ``require_role`` are thin wrappers over the
ladder and report as the tier they enforce.

Rows: ``{endpoint, methods, rule, file:line, gates, min_tier}``. A route with
no recognised gate reports ``(none)`` — the guard
``tests/unit/test_authz_oracle.py`` holds that set to the named anonymous
routes and fails the day another joins it.

Usage:  python scripts/authz_inventory.py          # markdown table to stdout
        python scripts/authz_inventory.py --json    # rows as JSON
"""
from __future__ import annotations

import inspect
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from primeqa.core.authz_gates import (  # noqa: E402 — round 4: the walker lives in the package
    NONE, gate_codes, gates_of, tier_in_closure, walk)

# the names the round-3 gate (tests/unit/test_authz_oracle.py) reads
_gate_codes, _walk, _tier_in_closure = gate_codes, walk, tier_in_closure


def extract(app=None) -> list[dict]:
    """One row per url_map rule of the live app (static excluded)."""
    if app is None:
        from primeqa.app import app as _app
        app = _app
    codes = gate_codes()
    rows = []
    for r in app.url_map.iter_rules():
        if r.endpoint == "static":
            continue
        fn = app.view_functions[r.endpoint]
        gates, tier = gates_of(fn, codes)
        target = inspect.unwrap(fn)
        try:
            src = os.path.relpath(inspect.getsourcefile(target), REPO)
            line = inspect.getsourcelines(target)[1]
        except (OSError, TypeError):
            src, line = "?", 0
        rows.append({
            "endpoint": r.endpoint,
            "methods": ",".join(sorted(m for m in r.methods if m not in ("HEAD", "OPTIONS"))),
            "rule": str(r.rule),
            "file": src, "line": line,
            "gates": gates or [NONE],
            "min_tier": tier.name if tier is not None else None,
        })
    rows.sort(key=lambda x: (x["rule"], x["methods"]))
    return rows


def main(argv=None) -> None:
    argv = sys.argv[1:] if argv is None else argv
    rows = extract()
    if "--json" in argv:
        json.dump(rows, sys.stdout, indent=1)
        return
    print("# Authorization inventory — from the LIVE app (round 3, AUD-001)")
    print()
    print(f"Generated by `scripts/authz_inventory.py`. {len(rows)} url_map rules; "
          f"{sum(1 for r in rows if r['gates'] == [NONE])} with no recognised gate.")
    print()
    print("| rule | methods | file:line | gates | min tier |")
    print("|---|---|---|---|---|")
    for r in rows:
        print(f"| `{r['rule']}` | {r['methods']} | {r['file']}:{r['line']} | "
              f"{'<br>'.join(r['gates'])} | {r['min_tier'] or ''} |")


if __name__ == "__main__":
    main()
